Add /llama3 command and fix bugs (#13)
* added groq command & openai endpoint support

* Rename OpenAI structs and types & remove test cuz cring

* better error handling

* removed unused parameters

* replaced to string into into

* changed function name and reordered parameters

* added max tokens

* usuń impl From<FormattedText> for CommandError
usuń impl std::fmt::Display for CommandError
zmień kolejność aliasów na ["llama3", "llama", "groq"]
usuń zmienne parts i parts_str
usuń komentarz // Convert text parts into a single string
dodaj parametr max_tokens do funkcji, wyślij go do api i ustaw na 256
domyślna temperatura

* inline some parameters

* changed command ordering and changed filename

* replaced match with response err

* fixed utf 8 panic but untested

* i think i fixed the makersuite.rs:110:80: error

* uh

* o to chodzilo??

* added PDF delay (untested)

* 5 second delay for all websites

* change case

* nitpicks

---------

Co-authored-by: jel <25802745+jelni@users.noreply.github.com>